/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DifficultyLevel = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Question {
  'id' : QuestionId,
  'difficultyLevel' : DifficultyLevel,
  'correctAnswer' : [] | [string],
  'questionText' : string,
  'subjectId' : SubjectId,
  'timestamp' : bigint,
  'category' : QuestionCategory,
  'options' : [] | [Array<string>],
}
export type QuestionCategory = { '_2Marks' : null } |
  { '_8Marks' : null } |
  { '_6Marks' : null } |
  { '_4Marks' : null } |
  { 'mcqOneMark' : null };
export type QuestionId = bigint;
export type SubjectId = string;
export interface _SERVICE {
  'addQuestion' : ActorMethod<
    [
      SubjectId,
      QuestionCategory,
      string,
      [] | [Array<string>],
      [] | [string],
      DifficultyLevel,
    ],
    undefined
  >,
  'addQuestionsInBulk' : ActorMethod<[Array<Question>], bigint>,
  'addSubject' : ActorMethod<[SubjectId, string, string], undefined>,
  'getAllVariants' : ActorMethod<[], Array<string>>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestionsBySubjectAndCategory' : ActorMethod<
    [SubjectId, QuestionCategory],
    Array<Question>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];