/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectId = IDL.Text;
export const QuestionCategory = IDL.Variant({
  'mcq' : IDL.Null,
  '_2Marks' : IDL.Null,
  '_8Marks' : IDL.Null,
  '_6Marks' : IDL.Null,
  '_4Marks' : IDL.Null,
});
export const DifficultyLevel = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'id' : QuestionId,
  'difficultyLevel' : DifficultyLevel,
  'correctAnswer' : IDL.Opt(IDL.Text),
  'questionText' : IDL.Text,
  'subjectId' : SubjectId,
  'timestamp' : IDL.Int,
  'category' : QuestionCategory,
  'options' : IDL.Opt(IDL.Vec(IDL.Text)),
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [
        SubjectId,
        QuestionCategory,
        IDL.Text,
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Text),
        DifficultyLevel,
      ],
      [],
      [],
    ),
  'addSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [], []),
  'getAllVariants' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getQuestionsBySubjectAndCategory' : IDL.Func(
      [SubjectId, QuestionCategory],
      [IDL.Vec(Question)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectId = IDL.Text;
  const QuestionCategory = IDL.Variant({
    'mcq' : IDL.Null,
    '_2Marks' : IDL.Null,
    '_8Marks' : IDL.Null,
    '_6Marks' : IDL.Null,
    '_4Marks' : IDL.Null,
  });
  const DifficultyLevel = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'id' : QuestionId,
    'difficultyLevel' : DifficultyLevel,
    'correctAnswer' : IDL.Opt(IDL.Text),
    'questionText' : IDL.Text,
    'subjectId' : SubjectId,
    'timestamp' : IDL.Int,
    'category' : QuestionCategory,
    'options' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [
          SubjectId,
          QuestionCategory,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Text),
          DifficultyLevel,
        ],
        [],
        [],
      ),
    'addSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [], []),
    'getAllVariants' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getQuestionsBySubjectAndCategory' : IDL.Func(
        [SubjectId, QuestionCategory],
        [IDL.Vec(Question)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };