/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaperVariant {
    questions: Array<QuestionId>;
    variant: string;
}
export interface GeneratedPaper {
    id: PaperId;
    totalMarks: bigint;
    subjectName: string;
    createdAt: bigint;
    setVariants: Array<PaperVariant>;
    subjectId: SubjectId;
    teacherId: Principal;
    questions: Array<QuestionId>;
    examDuration: bigint;
}
export type PaperId = bigint;
export type QuestionId = bigint;
export interface Question {
    id: QuestionId;
    difficultyLevel: DifficultyLevel;
    correctAnswer?: string;
    questionText: string;
    subjectId: SubjectId;
    timestamp: bigint;
    category: QuestionCategory;
    options?: Array<string>;
}
export type SubjectId = string;
export interface UserProfile {
    name: string;
    designation?: string;
    department?: string;
}
export interface Subject {
    code: string;
    name: string;
}
export enum DifficultyLevel {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum QuestionCategory {
    _2Marks = "_2Marks",
    _8Marks = "_8Marks",
    _6Marks = "_6Marks",
    _4Marks = "_4Marks",
    mcqOneMark = "mcqOneMark"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addQuestion(subjectId: SubjectId, category: QuestionCategory, questionText: string, options: Array<string> | null, correctAnswer: string | null, difficultyLevel: DifficultyLevel): Promise<QuestionId>;
    addQuestionsInBulk(questionsArray: Array<Question>): Promise<bigint>;
    addSubject(name: string, code: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deletePaper(id: PaperId): Promise<boolean>;
    deleteQuestion(id: QuestionId): Promise<boolean>;
    deleteSubject(id: SubjectId): Promise<boolean>;
    generatePaper(subjectId: SubjectId, examDuration: bigint, totalMarks: bigint, mcqCount: bigint, twoMarkCount: bigint, fourMarkCount: bigint, sixMarkCount: bigint, eightMarkCount: bigint): Promise<GeneratedPaper | null>;
    getAllVariants(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyPapers(): Promise<Array<GeneratedPaper>>;
    getPaper(id: PaperId): Promise<GeneratedPaper | null>;
    getPapers(): Promise<Array<GeneratedPaper>>;
    getQuestions(): Promise<Array<Question>>;
    getQuestionsBySubject(subjectId: SubjectId): Promise<Array<Question>>;
    getQuestionsBySubjectAndCategory(subjectId: SubjectId, category: QuestionCategory): Promise<Array<Question>>;
    getSubject(id: SubjectId): Promise<Subject | null>;
    getSubjects(): Promise<Array<Subject>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateQuestion(id: QuestionId, updatedQuestion: Question): Promise<boolean>;
    updateSubject(id: SubjectId, name: string, code: string): Promise<boolean>;
}
import type { DifficultyLevel as _DifficultyLevel, GeneratedPaper as _GeneratedPaper, Question as _Question, QuestionCategory as _QuestionCategory, QuestionId as _QuestionId, Subject as _Subject, SubjectId as _SubjectId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addQuestion(arg0: SubjectId, arg1: QuestionCategory, arg2: string, arg3: Array<string> | null, arg4: string | null, arg5: DifficultyLevel): Promise<QuestionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_DifficultyLevel_n5(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_DifficultyLevel_n5(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addQuestionsInBulk(arg0: Array<Question>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestionsInBulk(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestionsInBulk(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSubject(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deletePaper(arg0: PaperId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePaper(arg0);
            return result;
        }
    }
    async deleteQuestion(arg0: QuestionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: SubjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async generatePaper(arg0: SubjectId, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<GeneratedPaper | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePaper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePaper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVariants(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVariants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVariants();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPapers(): Promise<Array<GeneratedPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPapers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPapers();
            return result;
        }
    }
    async getPaper(arg0: PaperId): Promise<GeneratedPaper | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaper(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaper(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPapers(): Promise<Array<GeneratedPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapers();
            return result;
        }
    }
    async getQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsBySubject(arg0: SubjectId): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsBySubject(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsBySubject(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsBySubjectAndCategory(arg0: SubjectId, arg1: QuestionCategory): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsBySubjectAndCategory(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsBySubjectAndCategory(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubject(arg0: SubjectId): Promise<Subject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubject(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubject(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateQuestion(arg0: QuestionId, arg1: Question): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, to_candid_Question_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, to_candid_Question_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSubject(arg0: SubjectId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_DifficultyLevel_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionCategory): QuestionCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeneratedPaper]): GeneratedPaper | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subject]): Subject | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    designation: [] | [string];
    department: [] | [string];
}): {
    name: string;
    designation?: string;
    department?: string;
} {
    return {
        name: value.name,
        designation: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.designation)),
        department: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.department))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    difficultyLevel: _DifficultyLevel;
    correctAnswer: [] | [string];
    questionText: string;
    subjectId: _SubjectId;
    timestamp: bigint;
    category: _QuestionCategory;
    options: [] | [Array<string>];
}): {
    id: QuestionId;
    difficultyLevel: DifficultyLevel;
    correctAnswer?: string;
    questionText: string;
    subjectId: SubjectId;
    timestamp: bigint;
    category: QuestionCategory;
    options?: Array<string>;
} {
    return {
        id: value.id,
        difficultyLevel: from_candid_DifficultyLevel_n22(_uploadFile, _downloadFile, value.difficultyLevel),
        correctAnswer: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.correctAnswer)),
        questionText: value.questionText,
        subjectId: value.subjectId,
        timestamp: value.timestamp,
        category: from_candid_QuestionCategory_n24(_uploadFile, _downloadFile, value.category),
        options: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.options))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): DifficultyLevel {
    return "easy" in value ? DifficultyLevel.easy : "hard" in value ? DifficultyLevel.hard : "medium" in value ? DifficultyLevel.medium : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _2Marks: null;
} | {
    _8Marks: null;
} | {
    _6Marks: null;
} | {
    _4Marks: null;
} | {
    mcqOneMark: null;
}): QuestionCategory {
    return "_2Marks" in value ? QuestionCategory._2Marks : "_8Marks" in value ? QuestionCategory._8Marks : "_6Marks" in value ? QuestionCategory._6Marks : "_4Marks" in value ? QuestionCategory._4Marks : "mcqOneMark" in value ? QuestionCategory.mcqOneMark : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n20(_uploadFile, _downloadFile, x));
}
function to_candid_DifficultyLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): _DifficultyLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionCategory): _QuestionCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    designation?: string;
    department?: string;
}): {
    name: string;
    designation: [] | [string];
    department: [] | [string];
} {
    return {
        name: value.name,
        designation: value.designation ? candid_some(value.designation) : candid_none(),
        department: value.department ? candid_some(value.department) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: QuestionId;
    difficultyLevel: DifficultyLevel;
    correctAnswer?: string;
    questionText: string;
    subjectId: SubjectId;
    timestamp: bigint;
    category: QuestionCategory;
    options?: Array<string>;
}): {
    id: _QuestionId;
    difficultyLevel: _DifficultyLevel;
    correctAnswer: [] | [string];
    questionText: string;
    subjectId: _SubjectId;
    timestamp: bigint;
    category: _QuestionCategory;
    options: [] | [Array<string>];
} {
    return {
        id: value.id,
        difficultyLevel: to_candid_DifficultyLevel_n5(_uploadFile, _downloadFile, value.difficultyLevel),
        correctAnswer: value.correctAnswer ? candid_some(value.correctAnswer) : candid_none(),
        questionText: value.questionText,
        subjectId: value.subjectId,
        timestamp: value.timestamp,
        category: to_candid_QuestionCategory_n1(_uploadFile, _downloadFile, value.category),
        options: value.options ? candid_some(value.options) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionCategory): {
    _2Marks: null;
} | {
    _8Marks: null;
} | {
    _6Marks: null;
} | {
    _4Marks: null;
} | {
    mcqOneMark: null;
} {
    return value == QuestionCategory._2Marks ? {
        _2Marks: null
    } : value == QuestionCategory._8Marks ? {
        _8Marks: null
    } : value == QuestionCategory._6Marks ? {
        _6Marks: null
    } : value == QuestionCategory._4Marks ? {
        _4Marks: null
    } : value == QuestionCategory.mcqOneMark ? {
        mcqOneMark: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == DifficultyLevel.easy ? {
        easy: null
    } : value == DifficultyLevel.hard ? {
        hard: null
    } : value == DifficultyLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Array<_Question> {
    return value.map((x)=>to_candid_Question_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
