/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectId = IDL.Text;
export const QuestionCategory = IDL.Variant({
  '_2Marks' : IDL.Null,
  '_8Marks' : IDL.Null,
  '_6Marks' : IDL.Null,
  '_4Marks' : IDL.Null,
  'mcqOneMark' : IDL.Null,
});
export const DifficultyLevel = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'id' : QuestionId,
  'difficultyLevel' : DifficultyLevel,
  'correctAnswer' : IDL.Opt(IDL.Text),
  'questionText' : IDL.Text,
  'subjectId' : SubjectId,
  'timestamp' : IDL.Int,
  'category' : QuestionCategory,
  'options' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaperId = IDL.Nat;
export const PaperVariant = IDL.Record({
  'questions' : IDL.Vec(QuestionId),
  'variant' : IDL.Text,
});
export const GeneratedPaper = IDL.Record({
  'id' : PaperId,
  'totalMarks' : IDL.Int,
  'subjectName' : IDL.Text,
  'createdAt' : IDL.Int,
  'setVariants' : IDL.Vec(PaperVariant),
  'subjectId' : SubjectId,
  'teacherId' : IDL.Principal,
  'questions' : IDL.Vec(QuestionId),
  'examDuration' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'designation' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'code' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [
        SubjectId,
        QuestionCategory,
        IDL.Text,
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Text),
        DifficultyLevel,
      ],
      [QuestionId],
      [],
    ),
  'addQuestionsInBulk' : IDL.Func([IDL.Vec(Question)], [IDL.Nat], []),
  'addSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePaper' : IDL.Func([PaperId], [IDL.Bool], []),
  'deleteQuestion' : IDL.Func([QuestionId], [IDL.Bool], []),
  'deleteSubject' : IDL.Func([SubjectId], [IDL.Bool], []),
  'generatePaper' : IDL.Func(
      [
        SubjectId,
        IDL.Int,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Opt(GeneratedPaper)],
      [],
    ),
  'getAllVariants' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyPapers' : IDL.Func([], [IDL.Vec(GeneratedPaper)], ['query']),
  'getPaper' : IDL.Func([PaperId], [IDL.Opt(GeneratedPaper)], ['query']),
  'getPapers' : IDL.Func([], [IDL.Vec(GeneratedPaper)], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestionsBySubject' : IDL.Func(
      [SubjectId],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsBySubjectAndCategory' : IDL.Func(
      [SubjectId, QuestionCategory],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getSubject' : IDL.Func([SubjectId], [IDL.Opt(Subject)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateQuestion' : IDL.Func([QuestionId, Question], [IDL.Bool], []),
  'updateSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectId = IDL.Text;
  const QuestionCategory = IDL.Variant({
    '_2Marks' : IDL.Null,
    '_8Marks' : IDL.Null,
    '_6Marks' : IDL.Null,
    '_4Marks' : IDL.Null,
    'mcqOneMark' : IDL.Null,
  });
  const DifficultyLevel = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'id' : QuestionId,
    'difficultyLevel' : DifficultyLevel,
    'correctAnswer' : IDL.Opt(IDL.Text),
    'questionText' : IDL.Text,
    'subjectId' : SubjectId,
    'timestamp' : IDL.Int,
    'category' : QuestionCategory,
    'options' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaperId = IDL.Nat;
  const PaperVariant = IDL.Record({
    'questions' : IDL.Vec(QuestionId),
    'variant' : IDL.Text,
  });
  const GeneratedPaper = IDL.Record({
    'id' : PaperId,
    'totalMarks' : IDL.Int,
    'subjectName' : IDL.Text,
    'createdAt' : IDL.Int,
    'setVariants' : IDL.Vec(PaperVariant),
    'subjectId' : SubjectId,
    'teacherId' : IDL.Principal,
    'questions' : IDL.Vec(QuestionId),
    'examDuration' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'designation' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'code' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [
          SubjectId,
          QuestionCategory,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Text),
          DifficultyLevel,
        ],
        [QuestionId],
        [],
      ),
    'addQuestionsInBulk' : IDL.Func([IDL.Vec(Question)], [IDL.Nat], []),
    'addSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePaper' : IDL.Func([PaperId], [IDL.Bool], []),
    'deleteQuestion' : IDL.Func([QuestionId], [IDL.Bool], []),
    'deleteSubject' : IDL.Func([SubjectId], [IDL.Bool], []),
    'generatePaper' : IDL.Func(
        [
          SubjectId,
          IDL.Int,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Opt(GeneratedPaper)],
        [],
      ),
    'getAllVariants' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyPapers' : IDL.Func([], [IDL.Vec(GeneratedPaper)], ['query']),
    'getPaper' : IDL.Func([PaperId], [IDL.Opt(GeneratedPaper)], ['query']),
    'getPapers' : IDL.Func([], [IDL.Vec(GeneratedPaper)], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestionsBySubject' : IDL.Func(
        [SubjectId],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsBySubjectAndCategory' : IDL.Func(
        [SubjectId, QuestionCategory],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getSubject' : IDL.Func([SubjectId], [IDL.Opt(Subject)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateQuestion' : IDL.Func([QuestionId, Question], [IDL.Bool], []),
    'updateSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };