/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DifficultyLevel = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface GeneratedPaper {
  'id' : PaperId,
  'totalMarks' : bigint,
  'subjectName' : string,
  'createdAt' : bigint,
  'setVariants' : Array<PaperVariant>,
  'subjectId' : SubjectId,
  'teacherId' : Principal,
  'questions' : Array<QuestionId>,
  'examDuration' : bigint,
}
export type PaperId = bigint;
export interface PaperVariant {
  'questions' : Array<QuestionId>,
  'variant' : string,
}
export interface Question {
  'id' : QuestionId,
  'difficultyLevel' : DifficultyLevel,
  'correctAnswer' : [] | [string],
  'questionText' : string,
  'subjectId' : SubjectId,
  'timestamp' : bigint,
  'category' : QuestionCategory,
  'options' : [] | [Array<string>],
}
export type QuestionCategory = { '_2Marks' : null } |
  { '_8Marks' : null } |
  { '_6Marks' : null } |
  { '_4Marks' : null } |
  { 'mcqOneMark' : null };
export type QuestionId = bigint;
export interface Subject { 'code' : string, 'name' : string }
export type SubjectId = string;
export interface UserProfile {
  'name' : string,
  'designation' : [] | [string],
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<
    [
      SubjectId,
      QuestionCategory,
      string,
      [] | [Array<string>],
      [] | [string],
      DifficultyLevel,
    ],
    QuestionId
  >,
  'addQuestionsInBulk' : ActorMethod<[Array<Question>], bigint>,
  'addSubject' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePaper' : ActorMethod<[PaperId], boolean>,
  'deleteQuestion' : ActorMethod<[QuestionId], boolean>,
  'deleteSubject' : ActorMethod<[SubjectId], boolean>,
  'generatePaper' : ActorMethod<
    [SubjectId, bigint, bigint, bigint, bigint, bigint, bigint, bigint],
    [] | [GeneratedPaper]
  >,
  'getAllVariants' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPapers' : ActorMethod<[], Array<GeneratedPaper>>,
  'getPaper' : ActorMethod<[PaperId], [] | [GeneratedPaper]>,
  'getPapers' : ActorMethod<[], Array<GeneratedPaper>>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestionsBySubject' : ActorMethod<[SubjectId], Array<Question>>,
  'getQuestionsBySubjectAndCategory' : ActorMethod<
    [SubjectId, QuestionCategory],
    Array<Question>
  >,
  'getSubject' : ActorMethod<[SubjectId], [] | [Subject]>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateQuestion' : ActorMethod<[QuestionId, Question], boolean>,
  'updateSubject' : ActorMethod<[SubjectId, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];