/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type QuestionId = bigint;
export interface Question {
    id: QuestionId;
    difficultyLevel: DifficultyLevel;
    correctAnswer?: string;
    questionText: string;
    subjectId: SubjectId;
    timestamp: bigint;
    category: QuestionCategory;
    options?: Array<string>;
}
export type SubjectId = string;
export enum DifficultyLevel {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum QuestionCategory {
    mcq = "mcq",
    _2Marks = "_2Marks",
    _8Marks = "_8Marks",
    _6Marks = "_6Marks",
    _4Marks = "_4Marks"
}
export interface backendInterface {
    addQuestion(subjectId: SubjectId, category: QuestionCategory, questionText: string, options: Array<string> | null, correctAnswer: string | null, difficultyLevel: DifficultyLevel): Promise<void>;
    addSubject(id: SubjectId, name: string, code: string): Promise<void>;
    getAllVariants(): Promise<Array<string>>;
    getQuestionsBySubjectAndCategory(subjectId: SubjectId, category: QuestionCategory): Promise<Array<Question>>;
}
import type { DifficultyLevel as _DifficultyLevel, Question as _Question, QuestionCategory as _QuestionCategory, QuestionId as _QuestionId, SubjectId as _SubjectId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addQuestion(arg0: SubjectId, arg1: QuestionCategory, arg2: string, arg3: Array<string> | null, arg4: string | null, arg5: DifficultyLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_DifficultyLevel_n5(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_DifficultyLevel_n5(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addSubject(arg0: SubjectId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllVariants(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVariants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVariants();
            return result;
        }
    }
    async getQuestionsBySubjectAndCategory(arg0: SubjectId, arg1: QuestionCategory): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsBySubjectAndCategory(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsBySubjectAndCategory(arg0, to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DifficultyLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionCategory): QuestionCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    difficultyLevel: _DifficultyLevel;
    correctAnswer: [] | [string];
    questionText: string;
    subjectId: _SubjectId;
    timestamp: bigint;
    category: _QuestionCategory;
    options: [] | [Array<string>];
}): {
    id: QuestionId;
    difficultyLevel: DifficultyLevel;
    correctAnswer?: string;
    questionText: string;
    subjectId: SubjectId;
    timestamp: bigint;
    category: QuestionCategory;
    options?: Array<string>;
} {
    return {
        id: value.id,
        difficultyLevel: from_candid_DifficultyLevel_n10(_uploadFile, _downloadFile, value.difficultyLevel),
        correctAnswer: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.correctAnswer)),
        questionText: value.questionText,
        subjectId: value.subjectId,
        timestamp: value.timestamp,
        category: from_candid_QuestionCategory_n13(_uploadFile, _downloadFile, value.category),
        options: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.options))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): DifficultyLevel {
    return "easy" in value ? DifficultyLevel.easy : "hard" in value ? DifficultyLevel.hard : "medium" in value ? DifficultyLevel.medium : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mcq: null;
} | {
    _2Marks: null;
} | {
    _8Marks: null;
} | {
    _6Marks: null;
} | {
    _4Marks: null;
}): QuestionCategory {
    return "mcq" in value ? QuestionCategory.mcq : "_2Marks" in value ? QuestionCategory._2Marks : "_8Marks" in value ? QuestionCategory._8Marks : "_6Marks" in value ? QuestionCategory._6Marks : "_4Marks" in value ? QuestionCategory._4Marks : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n8(_uploadFile, _downloadFile, x));
}
function to_candid_DifficultyLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): _DifficultyLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionCategory): _QuestionCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionCategory): {
    mcq: null;
} | {
    _2Marks: null;
} | {
    _8Marks: null;
} | {
    _6Marks: null;
} | {
    _4Marks: null;
} {
    return value == QuestionCategory.mcq ? {
        mcq: null
    } : value == QuestionCategory._2Marks ? {
        _2Marks: null
    } : value == QuestionCategory._8Marks ? {
        _8Marks: null
    } : value == QuestionCategory._6Marks ? {
        _6Marks: null
    } : value == QuestionCategory._4Marks ? {
        _4Marks: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == DifficultyLevel.easy ? {
        easy: null
    } : value == DifficultyLevel.hard ? {
        hard: null
    } : value == DifficultyLevel.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
